version: '3.9'

services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    entrypoint:
      sh -c "
      printf 'CREATE DATABASE IF NOT EXISTS integrations;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb3 --collation-server=utf8mb3_general_ci --log_bin_trust_function_creators=1;"
    restart: always
    healthcheck:
      test: mysqladmin ping -ppass
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

    volumes:
      - ./data:/var/lib/mysql

networks:
  default:
    name: toolkit
    driver: bridge
